// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQbi2SA4H3LXG1N8MXKLUBVCqqZ4qXBU',
    appId: '1:282785094771:web:b9e8ae7f1d422badc35e06',
    messagingSenderId: '282785094771',
    projectId: 'local-tahong-market',
    authDomain: 'local-tahong-market.firebaseapp.com',
    storageBucket: 'local-tahong-market.firebasestorage.app',
    measurementId: 'G-DEVDLVVVG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdPxNvlJktzAvzxOmKOdoc-ncQY4Ut2X4',
    appId: '1:282785094771:android:fd6c4e8923b77d96c35e06',
    messagingSenderId: '282785094771',
    projectId: 'local-tahong-market',
    storageBucket: 'local-tahong-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6o0pDOdRx0M9bwSFsQbMUYI_3uofFujU',
    appId: '1:282785094771:ios:d655cf1e5ed7a634c35e06',
    messagingSenderId: '282785094771',
    projectId: 'local-tahong-market',
    storageBucket: 'local-tahong-market.firebasestorage.app',
    iosBundleId: 'com.example.localTahongMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6o0pDOdRx0M9bwSFsQbMUYI_3uofFujU',
    appId: '1:282785094771:ios:d655cf1e5ed7a634c35e06',
    messagingSenderId: '282785094771',
    projectId: 'local-tahong-market',
    storageBucket: 'local-tahong-market.firebasestorage.app',
    iosBundleId: 'com.example.localTahongMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyQbi2SA4H3LXG1N8MXKLUBVCqqZ4qXBU',
    appId: '1:282785094771:web:1b96490cc6c4bc69c35e06',
    messagingSenderId: '282785094771',
    projectId: 'local-tahong-market',
    authDomain: 'local-tahong-market.firebaseapp.com',
    storageBucket: 'local-tahong-market.firebasestorage.app',
    measurementId: 'G-T9JTWZSE07',
  );
}
